### ISSUE TITLE
monetary reward and level reward bugged

### ISSUE THREAD

**Issue by PortGasMC** [ezeiger92/QuestWorld2#111] opened 2018-03-17 17:34 UTC
hello 
as i said  monetary rewar and level reward bugged and players cant get there money and exp reward
pls fix this 
 thanks

**Comment by ezeiger92** [comment] 2018-03-18 16:40
What server and plugin versions do you have? I cannot replicate this using the latest QuestWorld and spigot 1.12.2.

**Comment by ezeiger92** [comment] 2018-03-18 17:45
I need to see your quest file, because I cannot reproduce this on my end using those settings. Please upload it to a pasting service or attach it to this thread.

**Comment by PortGasMC** [comment] 2018-03-18 18:02
[quests.zip](https://github.com/ezeiger92/QuestWorld2/files/1822986/quests.zip)


[config.zip](https://github.com/ezeiger92/QuestWorld2/files/1822987/config.zip)

**Comment by PortGasMC** [comment] 2018-03-18 18:03
hope this can help you

**Comment by ezeiger92** [comment] 2018-03-18 18:15
All but one of your quests have a cooldown of -1, meaning they can only be completed once. Are you sure you have not already completed those quests?

Try setting the cooldown to 0 ("Repeating") and clearing your player progress with `/qe reset <your name>`

**Comment by PortGasMC** [comment] 2018-03-18 18:16
ok ill check that 
thanks

**Comment by PortGasMC** [comment] 2018-03-18 18:18
btw im using the commands to set rewards until i manage to fix this 
thanks and i will check that

**Comment by PortGasMC** [comment] 2018-03-18 18:42
ezeiger92 i tried and cjange the quests cooldown and reset players
i completed the quests and theres no message of the money given and no message for the exp 
no reward money and exp

**Comment by ezeiger92** [comment] 2018-03-18 18:57
I just completed the `Pesca I` quest on my test server. The only change I made was allowing the world "World" because I'm not using a multi-world plugin, and I got the money and levels as expected.

If you give me your server IP, I can come on and take a look.

**Comment by PortGasMC** [comment] 2018-03-18 19:03
test server play.dlcraft.online

**Comment by ezeiger92** [comment] 2018-03-18 20:48
It seems weird that I had no trouble with the quest. I'm closing this ticket, but if you run into any other issues, just let me know and I can take a look

**Closed by ezeiger92** 2018-03-18 20:48 UTC
