### ISSUE TITLE
Autocomplete has stopped working.

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#10] opened 2017-04-22 08:52 UTC
I had many quests that would run a command when they were finish (automatically) but it seems to have stopped working. These commands was used to spawn monsters etc in dungeons so it was important they they got fired when the quest was done because then I would know where the player was. Now they have to click claim reward, witch usually means that they are far away and that they therefore dont get the challenge i have prepared for them.

The quests had not been changed since they used to work, so they should still work, However I double checked that autoreward was on.

**Comment by ezeiger92** [comment] 2017-04-22 18:34
Is this an issue with my recent push, or just a surprise that happened out of the blue?

If it's my latest push, I'd guess it's related to the cooldown change I made. If not... Well more stuff to fix!

**Comment by erik1988** [comment] 2017-04-22 19:03
I'm using the version you made Jan 3. I have no idea when it started to become a problem, but I know that these quests used to give the reward and the command before. I made sure the auto reward was checked and turned it off and on, but still seems like my players are having issues with those quests. 

I made a test quest right now where I used autoreward and a command as a reward, and it seems to work fine. So i'm a bit puzzled. I will try to do some more trubbleshooting and let you know when I know more.

**Comment by ezeiger92** [comment] 2017-05-07 23:38
Are you still having trouble with this, or did it magically fix itself? Could go either way with this plugin.

**Comment by erik1988** [comment] 2017-05-08 05:33
im still having issues. It seems to work well when I make a new quests, but on my old quests it does now work.

**Comment by ezeiger92** [comment] 2017-05-08 06:45
Could you send me one (or more) of the quests that's causing you trouble? I haven't managed to reproduce it yet.

**Comment by erik1988** [comment] 2017-05-17 06:42
This is one that was suppose to trigger a command automatically but it did not. I was watching when the players did this quests, so I know for sure. There is other quests like this that has the same issue, but when I tried to make a test quests it seems to work. 

Its hard for me to test the quests that dont work because they are in the end of a quest line etc.
I have not been able to test it after your latest version tho. 
http://txt.do/d9l2v

**Comment by ezeiger92** [comment] 2017-05-17 07:42
Say auto-claim rewards worked fine, but the location detector had an issue with that second task. I had to stand exactly on the block for a few seconds before it realized I completed the task.

I suspect the issue isn't auto-claim, but that you have such a small radius for the location that stuff isn't playing nice. Try increasing the radius on that second task and see if the issue gets better.

**Comment by erik1988** [comment] 2017-05-17 07:45
Well they do get that the task is finished. And they are able to click claim reward, when they do everything works as it suppose to. Hopefully things got better after the last update, I dont understnad why it does not work, since it worked when I tried to create a new test task.

**Comment by erik1988** [comment] 2017-05-17 09:49
I have asked some of my players and it seems to work well now. Perhaps it was related to the bug earlier that did not allow people to submit stuff. I will let you know if I find any other quests that is bugged.

**Comment by ezeiger92** [comment] 2017-05-17 09:55
Thanks mate! I'm closing this for now and will take a look at location detection later. Let me know if this suddenly becomes an issue again.

**Closed by ezeiger92** 2017-05-17 09:55 UTC
Labels: bug

**Comment by erik1988** [comment] 2017-05-17 09:58
I will. Thanks for making this plugin better, its greatly appreciated!
