### ISSUE TITLE
Citizens Submit Item Bug

### ISSUE THREAD

**Issue by Fharen** [ezeiger92/QuestWorld2#21] opened 2017-06-12 10:46 UTC
Using questworld 2.6.4 (the latest release on github page)
server version spigot 1.11.2

On citizens submit menu, The item slot for "items" does not update and is permanently a head (#0397/3).

**Comment by ezeiger92** [comment] 2017-06-12 17:06
Does the quest use the correct item when you try to complete it?

**Comment by ezeiger92** [comment] 2017-06-12 22:16
Looking at the code, it seems like this is just a visual "bug" due to copy/paste failure on my part, the quest should still function as intended. Pushing a fix for this shortly.

**Comment by ezeiger92** [comment] 2017-06-13 08:42
Should be fixed in the new release (2.6.5), let me know if this is still an issue.

**Closed by ezeiger92** 2017-06-13 08:42 UTC
Labels: bug
