### ISSUE TITLE
issues with getting kill count registered`?

### ISSUE THREAD

**Issue by erik1988** [ezeiger92/QuestWorld2#45] opened 2017-08-12 05:47 UTC
I have not tested this myself. But I have heard my players saying that certain kills does not get registered. 
One of them was a quest to kill the dragon 1 time. nobody got the quest finished, I dont know if it matters but the dragon was respawned. 

Another was someone saying they were not getting kills for killing zombies.

**Comment by Zicerite** [comment] 2017-08-12 05:52
I've only had this problem with "Named Mobs", i know that doesn't work (or im not doing it right, idk)

**Comment by ezeiger92** [comment] 2017-08-12 08:04
I'll take a look at KillNamed for sure, could you check if your quests were normal kill or named kill @erik1988?

**Comment by erik1988** [comment] 2017-08-12 14:18
No they were normal mobs without names.

Btw the zombie quest was "naturally spawned Zombie villagers".

**Comment by ezeiger92** [comment] 2017-08-12 21:56
Well named kill was completely broken, I assigned the name to customString, but never updated where I was checking, so it tested against displayName (which was never set). Woops. Looking into normal kill now.

**Comment by ezeiger92** [comment] 2017-08-12 22:20
Sorry @erik1988, I can't seem to replicate. I tried kill mob with zombie villager and enderdragon (respawned) both with spawners allowed and spawners denied, and tested across server restarts too.

Can you just triple check that you are using the "Kill Mob" mission (iron sword) and not the "Kill Named Mob" mission (gold sword)? It's either that or some bug in the build you have that I've already accidentally fixed in mine :x

**Comment by Zicerite** [comment] 2017-08-13 02:50
Maybe also have a "Contains word" too,
like, just for example, you have enemy dwarves, and there is like "Dwarven Archer" and "Dwarven Warrior", but they are different mobs for... mechanic reasons.

That or do something similar to the "Submit all" where the quest just becomes a checklist for the mobs you need to kill.

**Comment by ezeiger92** [comment] 2017-08-13 03:17
@Zicerite I can work on something, but you really should open a new issue unless it's directly related to the current one :P

**Comment by Zicerite** [comment] 2017-08-13 03:18
It seems i did both a request, and a comment relating to the issue, oops, my bad

**Comment by ezeiger92** [comment] 2017-08-13 23:01
@erik1988 Are you still having this issue, and made sure the mission wasn't accidentally "Kill Named Mob"? If so, please give me a quest file causing trouble and tell me your version of QuestWorld and Bukkit, otherwise I have no leads on this.

**Comment by ezeiger92** [comment] 2017-09-23 22:11
I could not reproduce this after testing the latest available version at the time of this report and have not heard back for a month, so I'm closing this. If you are still having an issue, please send me the quest file containing the mission causing trouble, otherwise I have no leads.

**Closed by ezeiger92** 2017-09-23 22:11 UTC
Labels: bug
