### ISSUE TITLE
Mine Quests Problem

### ISSUE THREAD

**Issue by MysticCity** [ezeiger92/QuestWorld2#60] opened 2017-11-18 11:23 UTC
Server Version: Spigot 1.12.2
Plugin: QuestWorld 2.6.8 (Decoupled Edition)

I have an Quest Mine xx of xx
I Try with Stone and many other Blocks and Seed and and and

All Time i Mine 1 Stone the Quest System say i mined 2 Stones

**Comment by ezeiger92** [comment] 2017-12-04 07:30
I can't see any reason this would happen. Do you have any plugins that mess with breaking blocks?

**Comment by MysticCity** [comment] 2017-12-04 10:14
No atm just worldedit,worldguard,essentials,questworld and serverlistplus

after restart the server it work fine....
this error is not all times

**Comment by ezeiger92** [comment] 2017-12-04 19:03
I have not been able to reproduce this issue.
[2.6.9.1](https://github.com/ezeiger92/QuestWorld2/releases) is the current version, could you try updating questworld (and any extensions) and let me know if you are still having this issue?

**Comment by ezeiger92** [comment] 2017-12-07 15:11
Hello?
Are you still having this issue in 2.6.9.1?

**Comment by MysticCity** [comment] 2017-12-07 17:32
sorry on 4 dez was my 30 B-day so i dont test anythink at this moment but i test this build and make an comment here okay

**Comment by ezeiger92** [comment] 2017-12-07 19:18
Right... So just noticed I tagged this instead of #66 in that commit, I didn't mean to do that. Ignore that message lol

**Comment by MysticCity** [comment] 2017-12-07 20:07
at this moment i can reproduce this error

**Comment by MysticCity** [comment] 2017-12-07 20:14
but you importer dont import all corectly ^^

the quest requirement dosnt import

**Comment by ezeiger92** [comment] 2017-12-08 01:21
Grab the build again, quest requirements now load.

Can you zip up your quests and send them to me?

**Comment by MysticCity** [comment] 2017-12-08 10:03
and again over 300 quests new requirements..... :(

**Comment by MysticCity** [comment] 2017-12-08 10:21
Here an error code:

08.12.2017 11:20:45 [WARNING] java.lang.NullPointerException
08.12.2017 11:20:45 [WARNING] 	at me.mrCookieSlime.QuestWorld.quest.Quest.setParent(Quest.java:377)
08.12.2017 11:20:45 [WARNING] 	at me.mrCookieSlime.QuestWorld.quest.QuestState.setParent(QuestState.java:96)
08.12.2017 11:20:45 [WARNING] 	at me.mrCookieSlime.QuestWorld.api.menu.QuestBook.lambda$openQuestEditor$35(QuestBook.java:930)
08.12.2017 11:20:45 [WARNING] 	at me.mrCookieSlime.QuestWorld.api.menu.Menu.click(Menu.java:114)
08.12.2017 11:20:45 [WARNING] 	at me.mrCookieSlime.QuestWorld.listener.MenuListener.onInventoryClick(MenuListener.java:26)
08.12.2017 11:20:45 [WARNING] 	at sun.reflect.GeneratedMethodAccessor382.invoke(Unknown Source)
08.12.2017 11:20:45 [WARNING] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
08.12.2017 11:20:45 [WARNING] 	at java.lang.reflect.Method.invoke(Unknown Source)
08.12.2017 11:20:45 [WARNING] 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
08.12.2017 11:20:45 [WARNING] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
08.12.2017 11:20:45 [WARNING] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499)
08.12.2017 11:20:45 [WARNING] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
08.12.2017 11:20:45 [WARNING] 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1884)
08.12.2017 11:20:45 [WARNING] 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
08.12.2017 11:20:45 [WARNING] 	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
08.12.2017 11:20:45 [WARNING] 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
08.12.2017 11:20:45 [WARNING] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
08.12.2017 11:20:45 [WARNING] 	at java.util.concurrent.FutureTask.run(Unknown Source)
08.12.2017 11:20:45 [WARNING] 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
08.12.2017 11:20:45 [WARNING] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
08.12.2017 11:20:45 [WARNING] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
08.12.2017 11:20:45 [WARNING] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
08.12.2017 11:20:45 [WARNING] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
08.12.2017 11:20:45 [WARNING] 	at java.lang.Thread.run(Unknown Source)


I missklick an requirement an right klick to remove this and got an internal error

**Comment by ezeiger92** [comment] 2017-12-08 19:20
Everything related to quest requirements is fixed now and doesn't belong in this ticket.

Again, can you zip up your quests and send them to me? I cannot reproduce a problem with the mine quests mission.

**Comment by MysticCity** [comment] 2017-12-09 12:46
not all but i can give you some no problem i uploade this files here at next week

**Comment by MysticCity** [comment] 2017-12-09 13:02
and again server stop / start and all requirements are lost

**Comment by MysticCity** [comment] 2017-12-09 13:09
ption: null
[14:07:07] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:09] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:11] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:12] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:14] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:16] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:18] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:19] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:21] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:22] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:24] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:25] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:27] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:28] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:30] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:31] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:33] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:34] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:36] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:37] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:39] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:40] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:41] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:43] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:44] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:46] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:48] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:49] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:50] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:52] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:53] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:55] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:56] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
[14:07:58] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null

**Comment by MysticCity** [comment] 2017-12-09 13:18
here is one of this quests from wood id: 1
category: 1
cooldown: -60000
name: 'Ich und mein Holz &8Stufe: &22'
item:
  ==: org.bukkit.inventory.ItemStack
  type: LOG
  amount: 2
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: 'Ich und mein Holz §8Stufe: §22'
    lore:
    - §7- §7Mine 64x Oak Wood
    - ''
    - §c§oLeft Click to edit
    - §c§oRight Click to delete
    ItemFlags:
    - HIDE_PLACED_ON
rewards:
  money: 0
  xp: 0
  commands: []
  items:
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND
    amount: 5
permission: ''
disable-parties: true
in-order: false
auto-claim: false
world-blacklist: []
min-party-size: 1
parent: 0-C1
missions:
  '54':
    item:
      ==: org.bukkit.inventory.ItemStack
      type: LOG
    amount: 320
    lore: Hey there! Do this Quest.
    index: 54
    type: MINE_BLOCK
    custom_string: ''
    timeframe: 0
    reset-on-death: false
    display-name: ''
    unique: 164
    location:
      world: Mystic-World
      x: 0.0
      y: 64.0
      z: 0.0
      pitch: 0.0
      yaw: 0.0
    entity: PLAYER
    custom_int: 0
    exclude-spawners: false

**Comment by MysticCity** [comment] 2017-12-09 13:19
At this moment we insert the requirements 4x
and all time i restart the server ALL lost
from harvest.... mine.... kill.... all

**Comment by ezeiger92** [comment] 2017-12-09 17:18
That section of you logs tells me nothing and doesn’t belong in this ticket. Put your full log file in a new ticket.

Every one of these releases was been marked “pre-release” because the plugin is going through many changes and prone to beaking. Make backups.

Just run `/qe export stuff` and send me `presets/stuff.zip`. Otherwise I cant help with *this* ticket.

**Comment by MysticCity** [comment] 2017-12-10 15:28
i make my backup but this syste remove all time the requiremens after starting a server

**Comment by MysticCity** [comment] 2017-12-10 18:28
[19:27:34] [Server thread/WARN]: [QuestWorld] Task #57 for QuestWorld v2.6.9.1 generated an exception
java.lang.NullPointerException: null
	at me.mrCookieSlime.QuestWorld.manager.PlayerManager.getStatus(PlayerManager.java:178) ~[?:?]
	at me.mrCookieSlime.QuestWorld.manager.PlayerManager.update(PlayerManager.java:145) ~[?:?]
	at me.mrCookieSlime.QuestWorld.QuestWorldPlugin.lambda$loadConfigs$1(QuestWorldPlugin.java:113) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-7754231-94b0980]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by ezeiger92** [comment] 2017-12-14 03:43
Have you had any more issues with mine quests giving too much progress since the last patch?

**Comment by MysticCity** [comment] 2017-12-14 12:36
no you can close it

if i got anny error i create a new ticket ^^

**Closed** 2017-12-14 15:49 UTC
Labels: bug
