### ISSUE TITLE
Error on Kill entity Change

### ISSUE THREAD

**Issue by RustyDagger** [ezeiger92/QuestWorld2#150] opened 2019-01-20 04:20 UTC
Ran into an error when trying to change the entity type on a Kill mission in the GUI editor.

I was holding a sword at first then I realized hmm maybe i should hold the spawn egg and it still complained and made errors Seems a little confusing as to how you expect me to set that setting maybe im still doing it wrong but none the less error..

https://pastebin.com/p24xuBpG

https://gyazo.com/606980c1821637fca8fc2c46294a7417
https://gyazo.com/13a14b7572dbf1dafb641dd6e9372730
https://gyazo.com/fcded5fee1d043cff252f65382f86567

**Comment by ezeiger92** [comment] 2019-01-20 21:16
Looks like the same issue posted later in #146 that should have been fixed in 2.8.0 alpha 2, which version are you running?

You don't need to hold a spawn egg, the button brings up a paged gui of all sorts of spawn eggs (and some other things)

**Comment by dallin1016** [comment] 2019-01-20 22:32
I can confirm it's fixed & working in 2.8.0 alpha 2 :)

**Comment by ezeiger92** [comment] 2019-01-20 22:48
Glad to hear it ^^
Let me know if you run into any other issues.

**Closed by ezeiger92** 2019-01-20 22:48 UTC
Labels: bug, duplicate
